# Site settings
title: Narendra Santhosh Nagarajan 
header-img: img/IMG_20160731_160241_HDR.jpg
email: santhoshnarendra@gmail.com
copyright_name: nagajothy
description: "Hello Everyone ! I am a Technology Entusiastic with my basics strong in Android , HTML , PHP , Hardware Embedded , many more.."
baseurl: ""
url: "https://www.narendra.co"
twitter_username: NARENDRASANTHO1
github_username:  santy_naren
facebook_username:  santhoshnarendra
email_username:  santhoshnarendra@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
